/** A dense one-screen reference — the bit people come back for. */
export const QUICK_REFERENCE: Array<{ element: string; syntax: string; id: string }> = [
  { element: 'Heading', syntax: '# H1  ## H2  ### H3', id: 'headings' },
  { element: 'Bold', syntax: '**bold text**', id: 'emphasis' },
  { element: 'Italic', syntax: '*italic text*', id: 'emphasis' },
  { element: 'Strikethrough', syntax: '~~struck text~~', id: 'strikethrough' },
  { element: 'Blockquote', syntax: '> quoted text', id: 'blockquotes' },
  { element: 'Ordered list', syntax: '1. First item', id: 'lists' },
  { element: 'Unordered list', syntax: '- First item', id: 'lists' },
  { element: 'Task list', syntax: '- [x] Done', id: 'task-lists' },
  { element: 'Inline code', syntax: '`code`', id: 'code' },
  { element: 'Code block', syntax: '```js … ```', id: 'code' },
  { element: 'Link', syntax: '[title](https://example.com)', id: 'links' },
  { element: 'Image', syntax: '![alt text](image.png)', id: 'images' },
  { element: 'Table', syntax: '| A | B |\n|---|---|', id: 'tables' },
  { element: 'Footnote', syntax: 'Text[^1]  [^1]: Note', id: 'footnotes' },
  { element: 'Horizontal rule', syntax: '---', id: 'horizontal-rules' },
  { element: 'Line break', syntax: 'end a line with \\', id: 'paragraphs' },
  { element: 'Alert', syntax: '> [!NOTE]', id: 'alerts' },
  { element: 'Math', syntax: '$E = mc^2$', id: 'math' },
  { element: 'Diagram', syntax: '```mermaid', id: 'diagrams' },
  { element: 'Emoji', syntax: ':rocket:', id: 'emoji' },
  { element: 'Escape', syntax: '\\*not italic\\*', id: 'escaping' },
  { element: 'Comment', syntax: '<!-- hidden -->', id: 'comments' },
]
